requires = ["tox>=4.19"]
env_list = [
    "py314",
    "py313",
    "py312",
    "py311",
    "py310",
    "py39",
    "py38",
    "py37",
    # "py36", -> not compatible due to scipy 1.6.0
    # "type"
]

[env_run_base]
description = "Run test under {base_python}"
deps = [
    "pytest",
    "PySide6;python_version>='3.10'",
    "PySide2>=5.15.2;python_version<'3.10'",
    # "PyQt5",
]
commands = [["pytest"]]

# [env.type]
# description = "run type check on code base"
# deps = [
#     "mypy==1.18.2",
#     "types-cachetools>=5.5.0.20240820",
#     "types-chardet>=5.0.4.6",
# ]
# commands = [["mypy", "scidatatool"], ["mypy", "Tests"]]
